---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: policies
  namespace: policies
spec:
  type: GitHub
  pathname: https://github.com/veniceofcode/policies-demo-blog.git

